# Problem Statement



<html> <font color = Darkblue>
The purpose is to predict whether the Pima Indian women shows signs of diabetes or not. We are using a dataset collected by "National Institute of Diabetes and Digestive and Kidney Diseases" which consists of a number of attributes which would help us to perform this prediction.
</font>
</html>

<html>
<font color = blue>
<b>Constraints on data collection </b>

</font>
</html>

<html> <font color = Darkblue>
All patients whose data has been collected are females at least 21 years old of Pima Indian heritage
</font>
</html>

In [1]:
#Import all the necessary modules
%matplotlib inline
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

#importing seaborn for statistical plots
import seaborn as sns

#Let us break the X and y dataframes into training set and test set. For this we will use
#Sklearn package's data splitting function which is based on random function

from sklearn.model_selection import train_test_split

import numpy as np

# calculate accuracy measures and confusion matrix
from sklearn import metrics


# Q1. Load the PIMA Indian Diabetes file into Python DataFrame. 


The file can be accessed directly from the URL (https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data or you may first download it to a local folder and then load it into Python dataframe.  Let us assume the data frame is named pima_df


In [25]:
colnames = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
pima_df= pd.read_csv("pima-indians-diabetes.data", names= colnames)

It is always a good practice to eye-ball raw data to get a feel of the data in terms of number of structure of the file, number of attributes, types of attributes and a general idea of likely challenges in the dataset. You would notice that it is a comma separated file. There are no column names!. Check the associated folders and find out about each attribute the name. What information is available about the data.

# Q2. Print 10 samples from the dataset

In [26]:
pima_df.head(10)

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1

# Q3 Print the datatypes of each column and the shape of the dataset 

In [27]:
#print data types of each column
print(pima_df.info())
#print shape of data set
print(pima_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
preg     768 non-null int64
plas     768 non-null int64
pres     768 non-null int64
skin     768 non-null int64
test     768 non-null int64
mass     768 non-null float64
pedi     768 non-null float64
age      768 non-null int64
class    768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
(768, 9)


There are '0's in the data. Are they really valid '0's or they are missing values?
Plasma, BP, skin thickness etc. these values cannot be 0.
look at column by column logically to understand this.


# Q4 Replace all the 0s in the column with the median of the same column value accordingly.

In [29]:
colnames_logic = ['plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age']
pima_df[colnames_logic] = pima_df[colnames_logic].replace({0:np.nan})
pima_df = pima_df.fillna(pima_df.median())
print(pima_df.head())

   preg   plas  pres  skin   test  mass   pedi   age  class
0     6  148.0  72.0  35.0  125.0  33.6  0.627  50.0      1
1     1   85.0  66.0  29.0  125.0  26.6  0.351  31.0      0
2     8  183.0  64.0  29.0  125.0  23.3  0.672  32.0      1
3     1   89.0  66.0  23.0   94.0  28.1  0.167  21.0      0
4     0  137.0  40.0  35.0  168.0  43.1  2.288  33.0      1


# Q5 Print the descriptive statistics of each & every column using describe() function

In [36]:
pima_df.describe().transpose()

count        mean        std     min        25%       50%        75%  \
preg   768.0    3.845052   3.369578   0.000    1.00000    3.0000    6.00000   
plas   768.0  121.656250  30.438286  44.000   99.75000  117.0000  140.25000   
pres   768.0   72.386719  12.096642  24.000   64.00000   72.0000   80.00000   
skin   768.0   29.108073   8.791221   7.000   25.00000   29.0000   32.00000   
test   768.0  140.671875  86.383060  14.000  121.50000  125.0000  127.25000   
mass   768.0   32.455208   6.875177  18.200   27.50000   32.3000   36.60000   
pedi   768.0    0.471876   0.331329   0.078    0.24375    0.3725    0.62625   
age    768.0   33.240885  11.760232  21.000   24.00000   29.0000   41.00000   
class  768.0    0.348958   0.476951   0.000    0.00000    0.0000    1.00000   

          max  
preg    17.00  
plas   199.00  
pres   122.00  
skin    99.00  
test   846.00  
mass    67.10  
pedi     2.42  
age     81.00  
class    1.00

# Q6 See the distribution of 'Class' variable and plot it using appropriate graph.

In [34]:
pima_df.groupby(["class"]).count()

preg  plas  pres  skin  test  mass  pedi  age
class                                               
0       500   500   500   500   500   500   500  500
1       268   268   268   268   268   268   268  268

#Just for your understanding - Using univariate analysis check the individual attributes for their basic statistic such as central values, spread, tails etc. What are your observations (any two attributes). Its an optional step and will not be graded.

Using bivariate analysis check for useful relationships between attributes and attributes and the target class



# Q7. Use pairplots and correlation method to observe the relationship between different variables and state your insights.
Hint: Use seaborn plot and check the relationship between different variables 


Using the plot - infer the relationship between different variables

# Q8 Split the pima_df into training and test set in the ratio of 70:30 (Training:Test).</b>


In [ ]:
#seaborn plot
sns.pairplot(pima_df, hue = "class")

In [49]:
array = pima_df.values
X = array[:,0:7] 
Y = array[:,8] 
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.30)

# Q9 Create the decision tree model using “entropy” method of reducing the entropy and fit it to training data.</b>



In [50]:
dt_model = DecisionTreeClassifier(criterion = 'entropy' )
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

# Q10 Print the accuracy of the model & print the confusion matrix 

In [52]:
#Accuracy of the model
print(dt_model.score(X_test , y_test))
print(dt_model.score(X_train , y_train))

0.7012987012987013
1.0


In [56]:
#confusion matrix
y_predict = dt_model.predict(X_test)
print(metrics.confusion_matrix(y_test, y_predict))

[[123  35]
 [ 34  39]]


Print the feature importance of the decision model - Optional

# Q12 Apply the Random forest model and print the accuracy of Random forest Model

In [60]:
from sklearn.ensemble import RandomForestClassifier
rfcl = RandomForestClassifier(n_estimators = 100)
rfcl = rfcl.fit(X_train, y_train)

In [61]:
y_predict = rfcl.predict(X_test)
print(rfcl.score(X_test , y_test))
print(metrics.confusion_matrix(y_test, y_predict))

0.7402597402597403
[[133  25]
 [ 35  38]]


# Q13 Apply Adaboost Ensemble Algorithm for the same data and print the accuracy.

In [62]:
from sklearn.ensemble import AdaBoostClassifier
#abcl = AdaBoostClassifier(base_estimator=dt_model, n_estimators=10)
abcl = AdaBoostClassifier( n_estimators=50)
abcl = abcl.fit(X_train, y_train)

In [64]:
y_predict = abcl.predict(X_test)
print(abcl.score(X_test , y_test))

print(metrics.confusion_matrix(y_test, y_predict))

0.7359307359307359
[[134  24]
 [ 37  36]]


# Q14 - Apply Bagging Classifier Algorithm and print the accuracy.

In [65]:
from sklearn.ensemble import BaggingClassifier

bgcl = BaggingClassifier(base_estimator=dt_model, n_estimators=50)
bgcl = bgcl.fit(X_train, y_train)

In [66]:
y_predict = bgcl.predict(X_test)

print(bgcl.score(X_test , y_test))

print(metrics.confusion_matrix(y_test, y_predict))

0.7532467532467533
[[133  25]
 [ 32  41]]


# Q15 - Apply GradientBoost Classifier Algorithm for the same data and print the accuracy

In [67]:
from sklearn.ensemble import GradientBoostingClassifier
gbcl = GradientBoostingClassifier(n_estimators = 50)
gbcl = gbcl.fit(X_train, y_train)


In [68]:
y_predict = gbcl.predict(X_test)
print(gbcl.score(X_test , y_test))
print(metrics.confusion_matrix(y_test, y_predict))

0.7186147186147186
[[130  28]
 [ 37  36]]


# Next steps are optional and will not be graded.

Voting is one of the simplest ways of combining the predictions from multiple machine learning algorithms.

It works by first creating two or more standalone models from your training dataset. A Voting Classifier can then be used to wrap your models and average the predictions of the sub-models when asked to make predictions for new data.

Apply Voting Classfier on the given dataset and state your insights.