### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### Load tensorflow

In [1]:
import tensorflow as tf
tf.set_random_seed(42)

C:\Users\Sahanaa_M\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'1.12.0'

### Collect Data

In [5]:
(trainX, trainY), (testX, testY) = tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 4s 1us/step


In [6]:
print(testY[0:5])

[9 2 1 1 6]


In [17]:
trainX.shape

(60000, 28, 28)

### Convert both training and testing labels into one-hot vectors.

**Hint:** check **tf.keras.utils.to_categorical()**

In [8]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

In [9]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
print('Number of Training examples: ', trainX.shape[0])

Number of Training examples:  60000


### Visualize the data

Plot first 10 images in the triaining set and their labels.

In [13]:
trainX[0:10]

array([[[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       ...,

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0

### Build a neural Network with a cross entropy loss function and sgd optimizer in Keras. The output layer with 10 neurons as we have 10 classes.

In [20]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Execute the model using model.fit()

In [21]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=10,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 6s 106us/step - loss: 13.0350 - acc: 0.1912 - val_loss: 12.8996 - val_acc: 0.1996
Epoch 2/10
60000/60000 [==============================] - 3s 57us/step - loss: 12.9179 - acc: 0.1985 - val_loss: 12.9219 - val_acc: 0.1983
Epoch 3/10
60000/60000 [==============================] - 3s 54us/step - loss: 12.9219 - acc: 0.1983 - val_loss: 12.9219 - val_acc: 0.1983
Epoch 4/10
60000/60000 [==============================] - 3s 54us/step - loss: 12.9219 - acc: 0.1983 - val_loss: 12.9219 - val_acc: 0.1983
Epoch 5/10
60000/60000 [==============================] - 3s 58us/step - loss: 12.9219 - acc: 0.1983 - val_loss: 12.9219 - val_acc: 0.1983
Epoch 6/10
60000/60000 [==============================] - 4s 59us/step - loss: 12.9219 - acc: 0.1983 - val_loss: 12.9219 - val_acc: 0.1983
Epoch 7/10
60000/60000 [==============================] - 3s 55us/step - loss: 12.9219 - acc: 0.1983 - val_loss: 12

### In the above Neural Network model add Batch Normalization layer after the input layer and repeat the steps.

In [24]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Execute the model

In [25]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=10,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 5s 89us/step - loss: 0.6003 - acc: 0.7949 - val_loss: 0.5229 - val_acc: 0.8193
Epoch 2/10
60000/60000 [==============================] - 4s 73us/step - loss: 0.4948 - acc: 0.8303 - val_loss: 0.4838 - val_acc: 0.8307
Epoch 3/10
60000/60000 [==============================] - 5s 82us/step - loss: 0.4710 - acc: 0.8385 - val_loss: 0.4809 - val_acc: 0.8326
Epoch 4/10
60000/60000 [==============================] - 5s 77us/step - loss: 0.4586 - acc: 0.8420 - val_loss: 0.4722 - val_acc: 0.8342
Epoch 5/10
60000/60000 [==============================] - 5s 75us/step - loss: 0.4506 - acc: 0.8446 - val_loss: 0.4734 - val_acc: 0.8388
Epoch 6/10
60000/60000 [==============================] - 4s 73us/step - loss: 0.4417 - acc: 0.8474 - val_loss: 0.4627 - val_acc: 0.8394
Epoch 7/10
60000/60000 [==============================] - 4s 73us/step - loss: 0.4402 - acc: 0.8473 - val_loss: 0.4669 - val_acc

### Customize the learning rate to 0.001 in sgd optimizer and run the model

In [26]:
#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.001)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [27]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_2 (Reshape)          (None, 784)               0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 784)               3136      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                7850      
Total params: 10,986
Trainable params: 9,418
Non-trainable params: 1,568
_________________________________________________________________


In [29]:
model.fit(trainX,trainY,          
          validation_data=(testX,testY),
          epochs=10,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 5s 77us/step - loss: 0.4096 - acc: 0.8569 - val_loss: 0.4583 - val_acc: 0.8422
Epoch 2/10
60000/60000 [==============================] - 5s 77us/step - loss: 0.4114 - acc: 0.8573 - val_loss: 0.4572 - val_acc: 0.8407
Epoch 3/10
60000/60000 [==============================] - 5s 77us/step - loss: 0.4122 - acc: 0.8558 - val_loss: 0.4557 - val_acc: 0.8425
Epoch 4/10
60000/60000 [==============================] - 5s 77us/step - loss: 0.4124 - acc: 0.8567 - val_loss: 0.4556 - val_acc: 0.8416
Epoch 5/10
60000/60000 [==============================] - 5s 81us/step - loss: 0.4124 - acc: 0.8571 - val_loss: 0.4505 - val_acc: 0.8421
Epoch 6/10
60000/60000 [==============================] - 5s 81us/step - loss: 0.4101 - acc: 0.8570 - val_loss: 0.4543 - val_acc: 0.8407
Epoch 7/10
60000/60000 [==============================] - 5s 80us/step - loss: 0.4105 - acc: 0.8566 - val_loss: 0.4592 - val_acc

### Build the Neural Network model with 3 Dense layers with 100,100,10 neurons respectively in each layer. Use cross entropy loss function and singmoid as activation in the hidden layers and softmax as activation function in the output layer. Use sgd optimizer with learning rate 0.03.

In [30]:
#Add 1st hidden layer
model.add(tf.keras.layers.Dense(100, activation='relu'))

In [31]:
#Add 2nd hidden layer
model.add(tf.keras.layers.Dense(100, activation='relu'))

In [32]:
#Add 3rd hidden layer
model.add(tf.keras.layers.Dense(10, activation='relu'))

In [33]:
#Add OUTPUT layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [34]:
#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

## Review model

In [35]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_2 (Reshape)          (None, 784)               0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 784)               3136      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                7850      
_________________________________________________________________
dense_3 (Dense)              (None, 100)               1100      
_________________________________________________________________
dense_4 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                1010      
_________________________________________________________________
dense_6 (Dense)              (None, 10)                110       
Total para

### Run the model

In [37]:
model.fit(trainX,trainY,          
          validation_data=(testX,testY),
          epochs=10,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 6s 93us/step - loss: 0.4255 - acc: 0.8597 - val_loss: 0.4961 - val_acc: 0.8392
Epoch 2/10
60000/60000 [==============================] - 6s 94us/step - loss: 0.4231 - acc: 0.8606 - val_loss: 0.4829 - val_acc: 0.8424
Epoch 3/10
60000/60000 [==============================] - 6s 94us/step - loss: 0.4215 - acc: 0.8607 - val_loss: 0.4742 - val_acc: 0.8464
Epoch 4/10
60000/60000 [==============================] - 6s 93us/step - loss: 0.4229 - acc: 0.8593 - val_loss: 0.4891 - val_acc: 0.8401
Epoch 5/10
60000/60000 [==============================] - 6s 94us/step - loss: 0.4240 - acc: 0.8597 - val_loss: 0.4907 - val_acc: 0.8393
Epoch 6/10
60000/60000 [==============================] - 6s 95us/step - loss: 0.4242 - acc: 0.8594 - val_loss: 0.4772 - val_acc: 0.8459
Epoch 7/10
60000/60000 [==============================] - 6s 95us/step - loss: 0.4194 - acc: 0.8603 - val_loss: 0.4820 - val_acc

In [38]:
model.save('mnist_dnn_keras_v1.h5')

In [ ]:
#Inference
#Optimizing by the model with the normalization, adding sgd optimizer, adding dense layers, batching graduaully reduces loss and increase