### Load tensorflow

In [1]:
import tensorflow as tf

C:\Users\Sahanaa_M\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#Reset Default graph - Needed only for Jupyter notebook
tf.reset_default_graph()

### Collect Data

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('prices.csv')

### Check all columns in the dataset

In [5]:
data.dtypes

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

### Drop columns `date` and  `symbol`

In [6]:
data=data.drop(['date','symbol'],axis=1)

In [7]:
data.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set

In [8]:
mini_data=data.head(1000)

In [10]:
mini_data.shape

(1000, 5)

### Divide the data into train and test sets

In [19]:
X = mini_data[['open','close','low','high']]
y = mini_data['volume']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

## Building the graph in tensorflow

1.Define input data placeholders

In [23]:
#Input features
x = tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')

x_n = tf.layers.batch_normalization(x, training=True)

#Actual Prices
y_ = tf.placeholder(shape=[None],dtype=tf.float32, name='y-input')

2.Define Weights and Bias

In [24]:
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]), name="Bias")

3.Prediction

In [25]:
y = tf.add(tf.matmul(x_n,W),b,name='output')

4.Loss (Cost) Function [Mean square error]

In [26]:
loss = tf.reduce_mean(tf.square(y-y_),name='Loss')

5.GradientDescent Optimizer to minimize Loss [GradientDescentOptimizer]

In [27]:
train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

## Execute the Graph for 100 epochs and observe the loss

In [28]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [30]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op, loss],feed_dict={x:X_train, 
                                                        y_:y_train})
    
    if epoch % 10 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  223195040000000.0
Training loss at step:  10  is  nan
Training loss at step:  20  is  nan
Training loss at step:  30  is  nan
Training loss at step:  40  is  nan
Training loss at step:  50  is  nan
Training loss at step:  60  is  nan
Training loss at step:  70  is  nan
Training loss at step:  80  is  nan
Training loss at step:  90  is  nan


### Get the shapes and values of W and b

Hint: Use sess.run(W) to get W.

In [35]:
sess.run(tf.shape(W))

array([4, 1])

In [36]:
sess.run(tf.shape(b))

array([1])

### Find the Absolute mean square loss difference between training and testing loss.

### Linear Classification using Keras

### Building the simple Neural Network in Keras with one neuron in the dense hidden layer.
#### Use Mean square error as loss function and sgd as optimizer

In [38]:
#Initialize Sequential Graph (model)
model = tf.keras.models.Sequential()

#Normalize input data
model.add(tf.keras.layers.BatchNormalization(input_shape=(4,)))

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

### Execute the model

In [39]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
700/700 [==============================] - 0s 450us/step - loss: nan          
Epoch 2/100
700/700 [==============================] - 0s 59us/step - loss: nan
Epoch 3/100
700/700 [==============================] - 0s 53us/step - loss: nan
Epoch 4/100
700/700 [==============================] - 0s 44us/step - loss: nan
Epoch 5/100
700/700 [==============================] - 0s 43us/step - loss: nan
Epoch 6/100
700/700 [==============================] - 0s 51us/step - loss: nan
Epoch 7/100
700/700 [==============================] - 0s 53us/step - loss: nan
Epoch 8/100
700/700 [==============================] - 0s 53us/step - loss: nan
Epoch 9/100
700/700 [==============================] - 0s 53us/step - loss: nan
Epoch 10/100
700/700 [==============================] - 0s 46us/step - loss: nan
Epoch 11/100
700/700 [==============================] - 0s 44us/step - loss: nan
Epoch 12/100
700/700 [==============================] - 0s 54us/step - loss: nan
Epoch 13/100
700/700 [====

### Classification using Keras 

In [40]:
import tensorflow as tf
tf.reset_default_graph()

### Load the given Iris data using pandas (Iris.csv)

In [42]:
data = pd.read_csv('iris.csv')

In [43]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

### Splitting the data into feature set and target set

In [48]:
X = data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = data[['Species']]

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [49]:
y_sklearn = y.copy()

from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
y_sklearn = lb_make.fit_transform(y)

#y_sklearn.head() 

C:\Users\Sahanaa_M\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [52]:
y_sklearn

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [53]:
one_hot = pd.get_dummies(y_sklearn)

In [54]:
one_hot

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
5    1  0  0
6    1  0  0
7    1  0  0
8    1  0  0
9    1  0  0
10   1  0  0
11   1  0  0
12   1  0  0
13   1  0  0
14   1  0  0
15   1  0  0
16   1  0  0
17   1  0  0
18   1  0  0
19   1  0  0
20   1  0  0
21   1  0  0
22   1  0  0
23   1  0  0
24   1  0  0
25   1  0  0
26   1  0  0
27   1  0  0
28   1  0  0
29   1  0  0
..  .. .. ..
120  0  0  1
121  0  0  1
122  0  0  1
123  0  0  1
124  0  0  1
125  0  0  1
126  0  0  1
127  0  0  1
128  0  0  1
129  0  0  1
130  0  0  1
131  0  0  1
132  0  0  1
133  0  0  1
134  0  0  1
135  0  0  1
136  0  0  1
137  0  0  1
138  0  0  1
139  0  0  1
140  0  0  1
141  0  0  1
142  0  0  1
143  0  0  1
144  0  0  1
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

### Divide the dataset into Training and test (70:30)

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y_sklearn, test_size=0.3, random_state=0)

### Model
Build the model with following layers: <br>
1. First dense layer with 10 neurons with input shape 4 (according to the feature set) <br>
2. Second Dense layer with 8 neurons <br>
3. Output layer with 3 neurons with softmax activation (output layer, 3 neurons as we have 3 classes) <br>
4. Use SGD and categorical_crossentropy loss 

In [67]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Normalize input data
model.add(tf.keras.layers.BatchNormalization(input_shape=(4,)))

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, activation='softmax'))

#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Fitting the model and predicting 

In [70]:
model.fit(X_train, y_sklearn.reshape(105), epochs=20)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [59]:
y_train.shape

(105,)

### Report Accuracy of the predicted values