### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### 1. Read the dataset

In [36]:
import tensorflow as tf
tf.set_random_seed(42)

In [2]:
tf.__version__

'1.12.0'

In [3]:
#Reset Default graph - Needed only for Jupyter notebook
tf.reset_default_graph()

In [4]:
import pandas as pd
data = pd.read_csv('bank.csv')

In [5]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

# 2. Drop the columns which are unique for all users like IDs

In [6]:
#dropping row number and customer id
data = data.iloc[:, 3:]

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()

data['Geography']= encoder.fit_transform(data['Geography'])
data['Gender']= encoder.fit_transform(data['Gender'])

In [8]:
data.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [9]:
data.shape

(10000, 11)

# Distinguish the feature and target set

In [10]:
features = data.drop('Exited', axis=1)

In [11]:
target = data["Exited"]

In [12]:
print('Number of examples: ', features.shape[0])
print('Number of features for each example: ', features.shape[1])

Number of examples:  10000
Number of features for each example:  10


# Divide the data set into Train and test sets

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=10)

# Normalize the train and test data 

In [14]:
#Input features
x = tf.placeholder(shape=[None,10],dtype=tf.float32, name='x-input')

#Normalize the data
x_n = tf.nn.l2_normalize(x,1)

#Actual Prices
y_ = tf.placeholder(shape=[None],dtype=tf.float32, name='y-input')

# Initialize & build the model

In [15]:
W = tf.Variable(tf.zeros(shape=[10,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

In [16]:
y = tf.add(tf.matmul(x_n,W),b,name='output')

In [17]:
loss = tf.reduce_mean(tf.square(y-y_),name='Loss')

# Optimize the model

In [18]:
train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

In [19]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 1000

In [22]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:features, y_:target})
    
    if epoch % 100 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  0.1477429
Training loss at step:  100  is  0.14775684
Training loss at step:  200  is  0.14777452
Training loss at step:  300  is  0.1477813
Training loss at step:  400  is  0.14778502
Training loss at step:  500  is  0.1477785
Training loss at step:  600  is  0.14777309
Training loss at step:  700  is  0.14776982
Training loss at step:  800  is  0.1477662
Training loss at step:  900  is  0.1477598


# Predict the results using 0.5 as a threshold 

In [73]:
model = tf.keras.models.Sequential()
#Normalize input data
model.add(tf.keras.layers.BatchNormalization(input_shape=(10,)))

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse', metrics=['accuracy'])

In [61]:
model.fit(features, target, epochs=100)

Epoch 1/100
10000/10000 [==============================] - 1s 83us/step - loss: 0.3758 - acc: 0.7377
Epoch 2/100
10000/10000 [==============================] - 0s 38us/step - loss: 0.1411 - acc: 0.8012
Epoch 3/100
10000/10000 [==============================] - 0s 38us/step - loss: 0.1405 - acc: 0.8032
Epoch 4/100
10000/10000 [==============================] - 0s 40us/step - loss: 0.1407 - acc: 0.8044
Epoch 5/100
10000/10000 [==============================] - 0s 40us/step - loss: 0.1403 - acc: 0.8040
Epoch 6/100
10000/10000 [==============================] - 0s 40us/step - loss: 0.1402 - acc: 0.8037
Epoch 7/100
10000/10000 [==============================] - 0s 39us/step - loss: 0.1402 - acc: 0.8042
Epoch 8/100
10000/10000 [==============================] - 0s 39us/step - loss: 0.1407 - acc: 0.8038
Epoch 9/100
10000/10000 [==============================] - 0s 39us/step - loss: 0.1405 - acc: 0.8032
Epoch 10/100
10000/10000 [==============================] - 0s 40us/step - loss: 0.1404 - a

10000/10000 [==============================] - 0s 39us/step - loss: 0.1407 - acc: 0.8014
Epoch 82/100
10000/10000 [==============================] - 0s 35us/step - loss: 0.1403 - acc: 0.8038
Epoch 83/100
10000/10000 [==============================] - 0s 38us/step - loss: 0.1407 - acc: 0.8025
Epoch 84/100
10000/10000 [==============================] - 0s 36us/step - loss: 0.1401 - acc: 0.8017
Epoch 85/100
10000/10000 [==============================] - 0s 38us/step - loss: 0.1404 - acc: 0.8060
Epoch 86/100
10000/10000 [==============================] - 0s 36us/step - loss: 0.1404 - acc: 0.8030
Epoch 87/100
10000/10000 [==============================] - 0s 35us/step - loss: 0.1409 - acc: 0.8013
Epoch 88/100
10000/10000 [==============================] - 0s 37us/step - loss: 0.1405 - acc: 0.8050
Epoch 89/100
10000/10000 [==============================] - 0s 35us/step - loss: 0.1404 - acc: 0.8036
Epoch 90/100
10000/10000 [==============================] - 0s 37us/step - loss: 0.1404 - acc: 

In [64]:
y_pred = model.predict(X_test)

In [69]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 100)               1100      
Total params: 1,100
Trainable params: 1,100
Non-trainable params: 0
_________________________________________________________________


In [67]:
y_test.shape

(3000,)

In [68]:
y_pred.shape

(3000, 100)

# Print the Accuracy score and confusion matrix 

In [71]:
import numpy as np
#y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [72]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

C:\Users\Sahanaa_M\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Sahanaa_M\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00      2380
           1       0.00      0.00      0.00       620
          32       0.00      0.00      0.00         0
          42       0.00      0.00      0.00         0
          58       0.00      0.00      0.00         0

   micro avg       0.00      0.00      0.00      3000
   macro avg       0.00      0.00      0.00      3000
weighted avg       0.00      0.00      0.00      3000

[[   0    0  886 1491    3]
 [   0    0  155  463    2]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]]
